# Generated by Django 6.0.1 on 2026-02-09 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(80)])),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('height_cm', models.PositiveIntegerField()),
                ('weight_kg', models.PositiveIntegerField()),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner (new to training)'), ('intermediate', 'Intermediate (train occasionally)'), ('advanced', 'Advanced (train consistently)')], max_length=30)),
                ('training_experience', models.CharField(choices=[('none', 'None'), ('home', 'Home workouts'), ('gym', 'Gym workouts'), ('personal_training', 'Personal training')], max_length=30)),
                ('health_considerations', models.TextField(blank=True)),
                ('primary_goal', models.CharField(choices=[('lose_weight', 'Lose weight'), ('build_muscle', 'Build muscle'), ('improve_endurance', 'Improve endurance'), ('increase_flexibility', 'Increase flexibility'), ('general_fitness', 'General fitness')], max_length=40)),
                ('secondary_goals', models.CharField(blank=True, max_length=255)),
                ('target_weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_timeframe', models.CharField(choices=[('1_3_months', '1–3 months'), ('3_6_months', '3–6 months'), ('6_plus', '6+ months')], max_length=20)),
                ('training_type', models.CharField(choices=[('home', 'Home training'), ('gym', 'Gym training'), ('hybrid', 'Hybrid (both)')], max_length=20)),
                ('workout_frequency', models.CharField(choices=[('2_3_days', '2–3 days'), ('3_4_days', '3–4 days'), ('5_plus_days', '5+ days')], max_length=20)),
                ('workout_duration', models.CharField(choices=[('20_30', '20–30 minutes'), ('30_45', '30–45 minutes'), ('45_60', '45–60 minutes')], max_length=20)),
                ('training_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('flexible', 'Flexible')], max_length=20)),
                ('equipment_home', models.CharField(choices=[('none', 'None'), ('dumbbells', 'Dumbbells'), ('bands', 'Resistance bands'), ('full_home_gym', 'Full home gym')], max_length=20)),
                ('gym_access', models.CharField(choices=[('no_access', 'No gym access'), ('commercial', 'Commercial gym'), ('private', 'Private gym')], max_length=20)),
                ('personal_coaching', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe later')], max_length=20)),
                ('coaching_style', models.CharField(choices=[('strict', 'Strict & structured'), ('supportive', 'Supportive & flexible'), ('mixed', 'Mixed')], max_length=20)),
                ('instructor_preference', models.CharField(blank=True, choices=[('male', 'Male trainer'), ('female', 'Female trainer'), ('no_preference', 'No preference')], max_length=20)),
                ('tracking_metrics', models.CharField(blank=True, max_length=255)),
                ('progress_check_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('commitment_level', models.CharField(choices=[('casual', 'Casual'), ('serious', 'Serious'), ('very_serious', 'Very serious')], max_length=20)),
                ('consent_acknowledged', models.BooleanField(default=False)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
