# Generated by Django 6.0.1 on 2026-03-06 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_workoutsessionevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTimetablePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='workoutsessionevent',
            new_name='gym_workout_user_id_6c7b2e_idx',
            old_name='gym_workout_user_id_7fee4b_idx',
        ),
        migrations.AddField(
            model_name='mealtimetableplan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_timetable_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
